# Generated by Django 3.1.2 on 2020-10-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
